name: "units-test"
on:
  pull_request:
    branches: main
    types:
      - closed

jobs:
  # test action works running from the graph
  test:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set Version
        id: version
        run: |
          echo "::set-output name=value::$( pwsh ./version-tool.ps1 next-version )"

      - name: Create a tag
        id: tag
        uses: ./
        with:
          github_token: ${{ secrets.NEW_GITHUB_TOKEN }}
          message: created ${{ steps.tag_version.outputs.new_tag }}
          tag: v${{ steps.tag_version.outputs.new_tag }}

      - name: Show Ref
        run: |
          echo "Created version ${{ steps.tag_version.outputs.ref }}"
